// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Data1.proto

package com.auzmor.assignement.controller;

public interface PersonOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Person)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required string name = 1;</code>
   */
  boolean hasName();
  /**
   * <code>required string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <code>required string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>required .Person.Gender gender = 2;</code>
   */
  boolean hasGender();
  /**
   * <code>required .Person.Gender gender = 2;</code>
   */
  com.auzmor.assignement.controller.Person.Gender getGender();

  /**
   * <code>optional sint32 age = 3;</code>
   */
  boolean hasAge();
  /**
   * <code>optional sint32 age = 3;</code>
   */
  int getAge();
}
